mode: "embedding"
tag: "Conv2Item"
query_instr: "Retrieve relevant items based on user conversation history:"
doc_instr: "Represent the item description for retrieval:"
from_json: "training/CRS_data/redial/test_processed_rec.jsonl"
db_json: "training/CRS_data/redial/redial_item_db.jsonl"
embeddings_path: "training/CRS_data/redial/redial_item_embeddings.pt"
base_model_path: "GritLM/GritLM-7B"
target_model_path: "model_weights/ReFICR_qlora"
use_image_features: true
image_embeddings_path: "training/CRS_data/posters/redial_clip_embeddings.pt"
image_fusion_weight: 0.2
image_projection_checkpoint: "model_weights/ReFICR_qlora/checkpoint-28712"
to_json: "training/CRS_data/redial/test_processed_cand.jsonl"
